DomainName: dev.optimizor.app
LoadBalancerHost: ""
CloudService: azure
ClusterType: talos
ClusterCAIssuer: ""
SocialIntegration: "teams"
SlackURL: "slack.com"
SlackChannel: "intelops"
TeamsURL: "teams.com"
TeamsChannel: "intelops"
